const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.destroy,
		C3.Plugins.Keyboard,
		C3.Behaviors.solid,
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Behaviors.jumpthru,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Behaviors.Platform.Acts.SetGravity,
		C3.Behaviors.jumpthru.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.IsOverlappingOffset,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.System.Acts.Wait,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.System.Acts.ResetEventVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.SaveState,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.System.Cnds.Else,
		C3.Behaviors.Platform.Cnds.CompareSpeed,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.LoadState,
		C3.Plugins.Sprite.Acts.AddInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{CentrarEm: 0},
	{DestruirForaDoLayout: 0},
	{KapivaraKid: 0},
	{Teclado: 0},
	{BackgroundParqueAquaticoParte: 0},
	{Sólido: 0},
	{PlataformaParqueAquatico: 0},
	{ChãoParqueAquatico: 0},
	{Vida_Formiga: 0},
	{Senóide: 0},
	{FormigaBoxeadora: 0},
	{Moeda: 0},
	{TEXTO2: 0},
	{ID: 0},
	{HEART: 0},
	{PlataformaPlanta: 0},
	{BarraDeEnergia: 0},
	{TEXTO3: 0},
	{GameOver: 0},
	{Reset: 0},
	{Camera: 0},
	{blocoD: 0},
	{Vida_CobraCoral: 0},
	{CobraCoral: 0},
	{Girar: 0},
	{Projétil: 0},
	{Shuriken: 0},
	{Base_solido: 0},
	{Mouse: 0},
	{Shuriken_HUD: 0},
	{PortãoD: 0},
	{PortãoE: 0},
	{Carrapato: 0},
	{TEXTO: 0},
	{Agua: 0},
	{Chão_afogado: 0},
	{Barril: 0},
	{SkyBackground: 0},
	{PularAtravés: 0},
	{Privada: 0},
	{Barreira_1: 0},
	{Vida_GataNinja: 0},
	{GataNinja: 0},
	{BackgroundAquario: 0},
	{WaterBackground: 0},
	{encanamento_1: 0},
	{encanamento_2: 0},
	{encanamento_3: 0},
	{Vida_PeixePiranha: 0},
	{PeixePiranha: 0},
	{VidaExtra: 0},
	{PatoSamurai: 0},
	{TEXTO4: 0},
	{Escada_1: 0},
	{Escada_2: 0},
	{Moeda_Hud: 0},
	{Fundo_PretoHUD: 0},
	{ChãoParqueAquatico2: 0},
	{Vida_SucuriAmarela: 0},
	{SucuriAmarela: 0},
	{Barreira_2: 0},
	{Escorregador: 0},
	{VIDAS: 0},
	{Moedas: 0},
	{Energia: 0},
	{vivo: 0},
	{Camera_Parado: 0},
	{kapi_anima: 0},
	{atirando: 0},
	{Quantidade_Shuriken: 0},
	{mysave: 0},
	{SubirEscada: 0},
	{shuriken_angulo: 0}
];

self.InstanceType = {
	KapivaraKid: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	BackgroundParqueAquaticoParte: class extends self.ISpriteInstance {},
	PlataformaParqueAquatico: class extends self.ISpriteInstance {},
	ChãoParqueAquatico: class extends self.ITiledBackgroundInstance {},
	FormigaBoxeadora: class extends self.ISpriteInstance {},
	Moeda: class extends self.ISpriteInstance {},
	TEXTO2: class extends self.ITextInstance {},
	HEART: class extends self.ISpriteInstance {},
	PlataformaPlanta: class extends self.ISpriteInstance {},
	BarraDeEnergia: class extends self.ISpriteInstance {},
	TEXTO3: class extends self.ITextInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Reset: class extends self.ISpriteInstance {},
	Camera: class extends self.ISpriteInstance {},
	blocoD: class extends self.ISpriteInstance {},
	CobraCoral: class extends self.ISpriteInstance {},
	Shuriken: class extends self.ISpriteInstance {},
	Base_solido: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Shuriken_HUD: class extends self.ISpriteInstance {},
	PortãoD: class extends self.ISpriteInstance {},
	PortãoE: class extends self.ISpriteInstance {},
	Carrapato: class extends self.ISpriteInstance {},
	TEXTO: class extends self.ITextInstance {},
	Agua: class extends self.ISpriteInstance {},
	Chão_afogado: class extends self.ISpriteInstance {},
	Barril: class extends self.ISpriteInstance {},
	SkyBackground: class extends self.ISpriteInstance {},
	Privada: class extends self.ISpriteInstance {},
	Barreira_1: class extends self.ISpriteInstance {},
	GataNinja: class extends self.ISpriteInstance {},
	BackgroundAquario: class extends self.ISpriteInstance {},
	WaterBackground: class extends self.ISpriteInstance {},
	encanamento_1: class extends self.ISpriteInstance {},
	encanamento_2: class extends self.ISpriteInstance {},
	encanamento_3: class extends self.ISpriteInstance {},
	PeixePiranha: class extends self.ISpriteInstance {},
	VidaExtra: class extends self.ISpriteInstance {},
	PatoSamurai: class extends self.ISpriteInstance {},
	TEXTO4: class extends self.ITextInstance {},
	Escada_1: class extends self.ISpriteInstance {},
	Escada_2: class extends self.ISpriteInstance {},
	Moeda_Hud: class extends self.ISpriteInstance {},
	Fundo_PretoHUD: class extends self.ISpriteInstance {},
	ChãoParqueAquatico2: class extends self.ITiledBackgroundInstance {},
	SucuriAmarela: class extends self.ISpriteInstance {},
	Barreira_2: class extends self.ISpriteInstance {},
	Escorregador: class extends self.ISpriteInstance {}
}